#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("customer_client.Resource", IsApplication=true)]

namespace customer_client
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::ZXing.Mobile.Resource.Id.contentFrame = global::customer_client.Resource.Id.contentFrame;
			global::ZXing.Mobile.Resource.Layout.zxingscanneractivitylayout = global::customer_client.Resource.Layout.zxingscanneractivitylayout;
			global::ZXing.Mobile.Resource.Layout.zxingscannerfragmentlayout = global::customer_client.Resource.Layout.zxingscannerfragmentlayout;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f050001
			public const int theme_devicedefault_background = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int white = 2131034112;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int background = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int BasicDing = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int burger = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int chickenTacos = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int cibus01 = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int cibus02 = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int cibus03 = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int cibus04 = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int cibus05 = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int citrus = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int facebook = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int facebook2 = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int friedGyoza = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int glazedGingerBeef = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int icecream = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int Icon = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int lobsterCake = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int lorem = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int lorem2 = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int OrangeLogo = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int pasta = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int pizza = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int primeRib = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int QBLogo = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int rodneysCafe = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int soda = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int steakFrites = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int strawberryMousse = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int tunaTataki = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int twoOneBistro = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int twoOneBurger = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int waffleBurger = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int water = 2130837536;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f07000d
			public const int Description = 2131165197;
			
			// aapt resource value: 0x7f07000b
			public const int Thumbnail = 2131165195;
			
			// aapt resource value: 0x7f07000c
			public const int Title = 2131165196;
			
			// aapt resource value: 0x7f070004
			public const int addButton = 2131165188;
			
			// aapt resource value: 0x7f07001a
			public const int backToMenu = 2131165210;
			
			// aapt resource value: 0x7f070018
			public const int callWaiter = 2131165208;
			
			// aapt resource value: 0x7f070020
			public const int contentFrame = 2131165216;
			
			// aapt resource value: 0x7f070002
			public const int description = 2131165186;
			
			// aapt resource value: 0x7f07001c
			public const int dingBut = 2131165212;
			
			// aapt resource value: 0x7f07000f
			public const int emailAddress = 2131165199;
			
			// aapt resource value: 0x7f070008
			public const int enterTableNumber = 2131165192;
			
			// aapt resource value: 0x7f070014
			public const int facebook = 2131165204;
			
			// aapt resource value: 0x7f070000
			public const int foodName = 2131165184;
			
			// aapt resource value: 0x7f070007
			public const int getGRCode = 2131165191;
			
			// aapt resource value: 0x7f070006
			public const int getTableHeader = 2131165190;
			
			// aapt resource value: 0x7f070012
			public const int guestLogin = 2131165202;
			
			// aapt resource value: 0x7f070001
			public const int image = 2131165185;
			
			// aapt resource value: 0x7f07000a
			public const int imageView1 = 2131165194;
			
			// aapt resource value: 0x7f070016
			public const int itemListView = 2131165206;
			
			// aapt resource value: 0x7f070015
			public const int linearLayout1 = 2131165205;
			
			// aapt resource value: 0x7f070013
			public const int login = 2131165203;
			
			// aapt resource value: 0x7f070019
			public const int orderTable = 2131165209;
			
			// aapt resource value: 0x7f070011
			public const int password = 2131165201;
			
			// aapt resource value: 0x7f070003
			public const int price = 2131165187;
			
			// aapt resource value: 0x7f070005
			public const int relativeLayout1 = 2131165189;
			
			// aapt resource value: 0x7f07001e
			public const int res1But = 2131165214;
			
			// aapt resource value: 0x7f07001f
			public const int res2But = 2131165215;
			
			// aapt resource value: 0x7f07001d
			public const int searchView1 = 2131165213;
			
			// aapt resource value: 0x7f070009
			public const int tableSubmit = 2131165193;
			
			// aapt resource value: 0x7f07000e
			public const int textView1 = 2131165198;
			
			// aapt resource value: 0x7f070010
			public const int textView2 = 2131165200;
			
			// aapt resource value: 0x7f07001b
			public const int total = 2131165211;
			
			// aapt resource value: 0x7f070017
			public const int viewOrder = 2131165207;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int detail = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int getTable = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int ListViewItemRow = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Main = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int menuOrder = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int orderTable = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int resSelect = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int zxingscanneractivitylayout = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int zxingscannerfragmentlayout = 2130903048;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060000
			public const int Theme_Custom = 2131099648;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
